CREATE TABLE IF NOT EXISTS auth.users ( instance_id uuid, id uuid PRIMARY KEY, aud character varying, role character varying, email character varying, encrypted_password character varying, email_confirmed_at timestamptz, invited_at timestamptz, confirmation_token character varying, confirmation_sent_at timestamptz, recovery_token character varying, recovery_sent_at timestamptz, email_change_token_new character varying, email_change character varying, email_change_sent_at timestamptz, last_sign_in_at timestamptz, raw_app_meta_data jsonb, raw_user_meta_data jsonb, is_super_admin boolean, created_at timestamptz, updated_at timestamptz, phone text DEFAULT NULL::character varying, phone_confirmed_at timestamptz, phone_change text DEFAULT ''::character varying, phone_change_token character varying DEFAULT ''::character varying, phone_change_sent_at timestamptz, confirmed_at timestamptz GENERATED ALWAYS AS (LEAST(email_confirmed_at, phone_confirmed_at)) STORED, email_change_token_current character varying DEFAULT ''::character varying, email_change_confirm_status smallint DEFAULT 0 CHECK (email_change_confirm_status >= 0 AND email_change_confirm_status <= 2), banned_until timestamptz, reauthentication_token character varying DEFAULT ''::character varying, reauthentication_sent_at timestamptz, is_sso_user boolean DEFAULT false, deleted_at timestamptz, is_anonymous boolean DEFAULT false );

CREATE TABLE IF NOT EXISTS auth.refresh_tokens ( instance_id uuid, id bigint PRIMARY KEY DEFAULT nextval('auth.refresh_tokens_id_seq'::regclass), token character varying UNIQUE, user_id character varying, revoked boolean, created_at timestamptz, updated_at timestamptz, parent character varying, session_id uuid );

CREATE TABLE IF NOT EXISTS auth.instances ( id uuid PRIMARY KEY, uuid uuid, raw_base_config text, created_at timestamptz, updated_at timestamptz );

CREATE TABLE IF NOT EXISTS auth.audit_log_entries ( instance_id uuid, id uuid PRIMARY KEY, payload json, created_at timestamptz, ip_address character varying DEFAULT ''::character varying );

CREATE TABLE IF NOT EXISTS auth.schema_migrations ( version character varying PRIMARY KEY );

CREATE TABLE IF NOT EXISTS auth.identities ( provider_id text, user_id uuid, identity_data jsonb, provider text, last_sign_in_at timestamptz, created_at timestamptz, updated_at timestamptz, email text GENERATED ALWAYS AS (lower((identity_data ->> 'email'::text))) STORED, id uuid PRIMARY KEY DEFAULT gen_random_uuid() );

CREATE TABLE IF NOT EXISTS auth.sessions ( id uuid PRIMARY KEY, user_id uuid, created_at timestamptz, updated_at timestamptz, factor_id uuid, aal aal_level, not_after timestamptz, refreshed_at timestamp, user_agent text, ip inet, tag text, oauth_client_id uuid, refresh_token_hmac_key text, refresh_token_counter bigint, scopes text CHECK (char_length(scopes) <= 4096) );

CREATE TABLE IF NOT EXISTS auth.mfa_factors ( id uuid PRIMARY KEY, user_id uuid, friendly_name text, factor_type factor_type, status factor_status, created_at timestamptz, updated_at timestamptz, secret text, phone text, last_challenged_at timestamptz UNIQUE, web_authn_credential jsonb, web_authn_aaguid uuid, last_webauthn_challenge_data jsonb );

CREATE TABLE IF NOT EXISTS auth.mfa_challenges ( id uuid PRIMARY KEY, factor_id uuid, created_at timestamptz, verified_at timestamptz, ip_address inet, otp_code text, web_authn_session_data jsonb );

CREATE TABLE IF NOT EXISTS auth.mfa_amr_claims ( session_id uuid, created_at timestamptz, updated_at timestamptz, authentication_method text, id uuid PRIMARY KEY );

CREATE TABLE IF NOT EXISTS auth.sso_providers ( id uuid PRIMARY KEY, resource_id text CHECK (resource_id = NULL::text OR char_length(resource_id) > 0), created_at timestamptz, updated_at timestamptz, disabled boolean );

CREATE TABLE IF NOT EXISTS auth.sso_domains ( id uuid PRIMARY KEY, sso_provider_id uuid, domain text CHECK (char_length(domain) > 0), created_at timestamptz, updated_at timestamptz );

CREATE TABLE IF NOT EXISTS auth.saml_providers ( id uuid PRIMARY KEY, sso_provider_id uuid, entity_id text UNIQUE CHECK (char_length(entity_id) > 0), metadata_xml text CHECK (char_length(metadata_xml) > 0), metadata_url text CHECK (metadata_url = NULL::text OR char_length(metadata_url) > 0), attribute_mapping jsonb, created_at timestamptz, updated_at timestamptz, name_id_format text );

CREATE TABLE IF NOT EXISTS auth.saml_relay_states ( id uuid PRIMARY KEY, sso_provider_id uuid, request_id text CHECK (char_length(request_id) > 0), for_email text, redirect_to text, created_at timestamptz, updated_at timestamptz, flow_state_id uuid );

CREATE TABLE IF NOT EXISTS auth.flow_state ( id uuid PRIMARY KEY, user_id uuid, auth_code text, code_challenge_method code_challenge_method, code_challenge text, provider_type text, provider_access_token text, provider_refresh_token text, created_at timestamptz, updated_at timestamptz, authentication_method text, auth_code_issued_at timestamptz );

CREATE TABLE IF NOT EXISTS auth.one_time_tokens ( id uuid PRIMARY KEY, user_id uuid, token_type one_time_token_type, token_hash text CHECK (char_length(token_hash) > 0), relates_to text, created_at timestamp DEFAULT now(), updated_at timestamp DEFAULT now() );

CREATE TABLE IF NOT EXISTS auth.oauth_clients ( id uuid PRIMARY KEY, client_secret_hash text, registration_type oauth_registration_type, redirect_uris text, grant_types text, client_name text CHECK (char_length(client_name) <= 1024), client_uri text CHECK (char_length(client_uri) <= 2048), logo_uri text CHECK (char_length(logo_uri) <= 2048), created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), deleted_at timestamptz, client_type auth.oauth_client_type DEFAULT 'confidential'::auth.oauth_client_type );

CREATE TABLE IF NOT EXISTS auth.oauth_authorizations ( id uuid PRIMARY KEY, authorization_id text UNIQUE, client_id uuid, user_id uuid, redirect_uri text CHECK (char_length(redirect_uri) <= 2048), scope text CHECK (char_length(scope) <= 4096), state text CHECK (char_length(state) <= 4096), resource text CHECK (char_length(resource) <= 2048), code_challenge text CHECK (char_length(code_challenge) <= 128), code_challenge_method code_challenge_method, response_type oauth_response_type DEFAULT 'code'::auth.oauth_response_type, status oauth_authorization_status DEFAULT 'pending'::auth.oauth_authorization_status, authorization_code text UNIQUE CHECK (char_length(authorization_code) <= 255), created_at timestamptz DEFAULT now(), expires_at timestamptz DEFAULT (now() + '00:03:00'::interval), approved_at timestamptz, nonce text CHECK (char_length(nonce) <= 255) );

CREATE TABLE IF NOT EXISTS auth.oauth_consents ( id uuid PRIMARY KEY, user_id uuid, client_id uuid, scopes text CHECK (char_length(scopes) <= 2048), granted_at timestamptz DEFAULT now(), revoked_at timestamptz );

-- Schema: storage CREATE SCHEMA IF NOT EXISTS storage;

CREATE TABLE IF NOT EXISTS storage.buckets ( id text PRIMARY KEY, name text, owner uuid, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), public boolean DEFAULT false, avif_autodetection boolean DEFAULT false, file_size_limit bigint, allowed_mime_types text[], owner_id text, type storage.buckettype DEFAULT 'STANDARD'::storage.buckettype );

CREATE TABLE IF NOT EXISTS storage.objects ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), bucket_id text, name text, owner uuid, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), last_accessed_at timestamptz DEFAULT now(), metadata jsonb, path_tokens text[] GENERATED ALWAYS AS (string_to_array(name, '/'::text)) STORED, version text, owner_id text, user_metadata jsonb, level integer );

CREATE TABLE IF NOT EXISTS storage.migrations ( id integer PRIMARY KEY, name character varying UNIQUE, hash character varying, executed_at timestamp DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE IF NOT EXISTS storage.s3_multipart_uploads ( id text PRIMARY KEY, in_progress_size bigint DEFAULT 0, upload_signature text, bucket_id text, key text, version text, owner_id text, created_at timestamptz DEFAULT now(), user_metadata jsonb );

CREATE TABLE IF NOT EXISTS storage.s3_multipart_uploads_parts ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), upload_id text, size bigint DEFAULT 0, part_number integer, bucket_id text, key text, etag text, owner_id text, version text, created_at timestamptz DEFAULT now() );

CREATE TABLE IF NOT EXISTS storage.prefixes ( bucket_id text, name text, level integer GENERATED ALWAYS AS (storage.get_level(name)) STORED, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), PRIMARY KEY (bucket_id, name, level) );

CREATE TABLE IF NOT EXISTS storage.buckets_analytics ( name text, type storage.buckettype DEFAULT 'ANALYTICS'::storage.buckettype, format text DEFAULT 'ICEBERG'::text, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), id uuid PRIMARY KEY DEFAULT gen_random_uuid(), deleted_at timestamptz );

CREATE TABLE IF NOT EXISTS storage.buckets_vectors ( id text PRIMARY KEY, type storage.buckettype DEFAULT 'VECTOR'::storage.buckettype, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now() );

CREATE TABLE IF NOT EXISTS storage.vector_indexes ( id text PRIMARY KEY DEFAULT gen_random_uuid(), name text, bucket_id text, data_type text, dimension integer, distance_metric text, metadata_configuration jsonb, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now() );

-- Schema: vault CREATE SCHEMA IF NOT EXISTS vault;

CREATE TABLE IF NOT EXISTS vault.secrets ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text, description text DEFAULT ''::text, secret text, key_id uuid, nonce bytea DEFAULT vault.crypto_aead_det_noncegen(), created_at timestamptz DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz DEFAULT CURRENT_TIMESTAMP );

-- Schema: realtime CREATE SCHEMA IF NOT EXISTS realtime;

CREATE TABLE IF NOT EXISTS realtime.schema_migrations ( version bigint PRIMARY KEY, inserted_at timestamp );

CREATE TABLE IF NOT EXISTS realtime.subscription ( id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY, subscription_id uuid, entity regclass, filters realtime.user_defined_filter[] DEFAULT '{}'::realtime.user_defined_filter[], claims jsonb, claims_role regrole GENERATED ALWAYS AS (realtime.to_regrole((claims ->> 'role'::text))) STORED, created_at timestamp DEFAULT timezone('utc'::text, now()) );

CREATE TABLE IF NOT EXISTS realtime.messages ( topic text, extension text, payload jsonb, event text, private boolean DEFAULT false, updated_at timestamp DEFAULT now(), inserted_at timestamp DEFAULT now(), id uuid PRIMARY KEY DEFAULT gen_random_uuid() );

-- Schema: public CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS public."User" ( userid integer PRIMARY KEY DEFAULT nextval('"User_userid_seq"'::regclass), username character varying UNIQUE, password character varying, email character varying UNIQUE, role character varying );

CREATE TABLE IF NOT EXISTS public.company ( companyid integer PRIMARY KEY DEFAULT nextval('company_companyid_seq'::regclass), companyname character varying, address text, registrationdate date, userid integer );

CREATE TABLE IF NOT EXISTS public.questionnaire ( questionnaireid integer PRIMARY KEY DEFAULT nextval('questionnaire_questionnaireid_seq'::regclass), title character varying, version character varying, description text, standard character varying );

CREATE TABLE IF NOT EXISTS public.question ( questionid integer PRIMARY KEY DEFAULT nextval('question_questionid_seq'::regclass), questionnaireid integer, text text, type character varying, weight numeric, category character varying, require_evidence boolean DEFAULT false, options jsonb, created_at timestamptz DEFAULT CURRENT_TIMESTAMP, updated_at timestamptz DEFAULT CURRENT_TIMESTAMP, evidence_hint text, option_a text, option_b text, option_c text, option_d text, option_e text );

CREATE TABLE IF NOT EXISTS public.assessment ( assessmentid integer PRIMARY KEY DEFAULT nextval('assessment_assessmentid_seq'::regclass), companyid integer, questionnaireid integer, status character varying, finalscore numeric, startdate timestamp DEFAULT now(), completiondate timestamp );

CREATE TABLE IF NOT EXISTS public.answer ( answerid integer PRIMARY KEY DEFAULT nextval('answer_answerid_seq'::regclass), assessmentid integer, questionid integer, response text );

CREATE TABLE IF NOT EXISTS public.evidence ( evidenceid integer PRIMARY KEY DEFAULT nextval('evidence_evidenceid_seq'::regclass), answerid integer, filename character varying, filetype character varying, uploaddate timestamp DEFAULT now(), uploaderid integer, storagepath character varying );

CREATE TABLE IF NOT EXISTS public.report ( reportid integer PRIMARY KEY DEFAULT nextval('report_reportid_seq'::regclass), assessmentid integer UNIQUE, generateddate timestamp DEFAULT now(), format character varying, content text );

CREATE TABLE IF NOT EXISTS public.registrationrequest ( requestid integer PRIMARY KEY DEFAULT nextval('registrationrequest_requestid_seq'::regclass), username character varying, email character varying UNIQUE, password character varying, role character varying CHECK (role::text = ANY (ARRAY['user'::character varying, 'auditor'::character varying]::text[])), companyname character varying, address text, status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[])), rejection_reason text, requested_at timestamptz DEFAULT CURRENT_TIMESTAMP, reviewed_at timestamptz, reviewed_by integer );

-- Foreign key constraints (add after tables created) ALTER TABLE auth.refresh_tokens ADD CONSTRAINT refresh_tokens_session_id_fkey FOREIGN KEY (session_id) REFERENCES auth.sessions(id); ALTER TABLE auth.identities ADD CONSTRAINT identities_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id); ALTER TABLE auth.sessions ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id); ALTER TABLE auth.sessions ADD CONSTRAINT sessions_oauth_client_id_fkey FOREIGN KEY (oauth_client_id) REFERENCES auth.oauth_clients(id); ALTER TABLE auth.mfa_factors ADD CONSTRAINT mfa_factors_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id); ALTER TABLE auth.mfa_challenges ADD CONSTRAINT mfa_challenges_auth_factor_id_fkey FOREIGN KEY (factor_id) REFERENCES auth.mfa_factors(id); ALTER TABLE auth.mfa_amr_claims ADD CONSTRAINT mfa_amr_claims_session_id_fkey FOREIGN KEY (session_id) REFERENCES auth.sessions(id); ALTER TABLE auth.one_time_tokens ADD CONSTRAINT one_time_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id); ALTER TABLE auth.oauth_authorizations ADD CONSTRAINT oauth_authorizations_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.oauth_clients(id); ALTER TABLE auth.oauth_authorizations ADD CONSTRAINT oauth_authorizations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id); ALTER TABLE auth.oauth_consents ADD CONSTRAINT oauth_consents_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id); ALTER TABLE auth.oauth_consents ADD CONSTRAINT oauth_consents_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.oauth_clients(id);

ALTER TABLE storage.s3_multipart_uploads ADD CONSTRAINT s3_multipart_uploads_bucket_id_fkey FOREIGN KEY (bucket_id) REFERENCES storage.buckets(id); ALTER TABLE storage.s3_multipart_uploads_parts ADD CONSTRAINT s3_multipart_uploads_parts_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES storage.s3_multipart_uploads(id); ALTER TABLE storage.s3_multipart_uploads_parts ADD CONSTRAINT s3_multipart_uploads_parts_bucket_id_fkey FOREIGN KEY (bucket_id) REFERENCES storage.buckets(id); ALTER TABLE storage.objects ADD CONSTRAINT objects_bucketId_fkey FOREIGN KEY (bucket_id) REFERENCES storage.buckets(id); ALTER TABLE storage.prefixes ADD CONSTRAINT prefixes_bucketId_fkey FOREIGN KEY (bucket_id) REFERENCES storage.buckets(id); ALTER TABLE storage.buckets ADD CONSTRAINT s3_multipart_uploads_parts_bucket_id_fkey FOREIGN KEY (id) REFERENCES storage.s3_multipart_uploads_parts(bucket_id);

ALTER TABLE vault.secrets ADD CONSTRAINT vault_key_id_fkey FOREIGN KEY (key_id) REFERENCES vault.keys(id);

ALTER TABLE realtime.subscription ADD CONSTRAINT subscription_some_fkey FOREIGN KEY (/* none /) REFERENCES / none */; -- no direct foreigns available from metadata

ALTER TABLE public.company ADD CONSTRAINT company_userid_fkey FOREIGN KEY (userid) REFERENCES public."User"(userid); ALTER TABLE public.question ADD CONSTRAINT question_questionnaireid_fkey FOREIGN KEY (questionnaireid) REFERENCES public.questionnaire(questionnaireid); ALTER TABLE public.assessment ADD CONSTRAINT assessment_questionnaireid_fkey FOREIGN KEY (questionnaireid) REFERENCES public.questionnaire(questionnaireid); ALTER TABLE public.assessment ADD CONSTRAINT assessment_companyid_fkey FOREIGN KEY (companyid) REFERENCES public.company(companyid); ALTER TABLE public.answer ADD CONSTRAINT answer_assessmentid_fkey FOREIGN KEY (assessmentid) REFERENCES public.assessment(assessmentid); ALTER TABLE public.answer ADD CONSTRAINT answer_questionid_fkey FOREIGN KEY (questionid) REFERENCES public.question(questionid); ALTER TABLE public.evidence ADD CONSTRAINT evidence_answerid_fkey FOREIGN KEY (answerid) REFERENCES public.answer(answerid); ALTER TABLE public.evidence ADD CONSTRAINT evidence_uploaderid_fkey FOREIGN KEY (uploaderid) REFERENCES public."User"(userid); ALTER TABLE public.report ADD CONSTRAINT report_assessmentid_fkey FOREIGN KEY (assessmentid) REFERENCES public.assessment(assessmentid); ALTER TABLE public.registrationrequest ADD CONSTRAINT registrationrequest_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public."User"(userid);

INSERT INTO public.question (
  questionid, questionnaireid, text, type, weight, category, require_evidence, options, created_at, updated_at, evidence_hint, option_a, option_b, option_c, option_d, option_e
) VALUES
(94, 1, 'Has the company conducted comprehensive Environmental and Social Impact Assessments (ESIAs) before operations and developed management plans to address identified impacts?', 'multiple_choice', 500.00, 'Exploration & Planning', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'ESIA reports, management plans, approval documents', 'No impact assessments conducted.', 'ESIAs are planned or in draft, but not completed.', 'ESIAs completed and basic management plans exist, limited implementation.', 'Comprehensive ESIAs completed with mitigation plans implemented; effectiveness under review.', 'Full ESIA and management plans completed and integrated into operations (approved by regulators)'),
(95, 1, 'Does the company obtain Free, Prior, and Informed Consent (FPIC) from affected communities before beginning operations?', 'multiple_choice', 500.00, 'Exploration & Planning', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'Community agreements, consultation records', 'No FPIC process was conducted.', 'FPIC process planned or initiated, but no consent yet.', 'FPIC consultations underway with partial agreements.', 'FPIC obtained from most communities; process under review.', 'FPIC fully obtained from all affected communities and documented.'),
(96, 1, 'If the project involved displacement of people, does the company have a resettlement plan to fairly compensate and relocate affected communities?', 'multiple_choice', 400.00, 'Exploration & Planning', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'Resettlement action plan, compensation records', 'No resettlement plan or compensation provided.', 'Resettlement plan drafted, not yet implemented.', 'Resettlement plan in place and partially implemented (some compensation/relocation done).', 'Resettlement completed for all affected people; success being evaluated.', 'Resettlement fully carried out with fair compensation and livelihood restoration.'),
(97, 1, 'Does the company have an ongoing stakeholder engagement plan to keep local communities informed and involved throughout the project lifecycle?', 'multiple_choice', 300.00, 'Exploration & Planning', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'Stakeholder engagement plan, meeting minutes', 'No formal stakeholder engagement plan.', 'Stakeholder engagement plans exist on paper, not implemented.', 'Stakeholder engagement plan implemented in part (occasional meetings).', 'Regular stakeholder engagements occur; feedback is reviewed for improvement.', 'Continuous stakeholder engagement is fully integrated into decision-making.'),
(98, 1, 'Does the company have a mine closure plan (including land reclamation) with clearly allocated financial assurance for closure and reclamation costs?', 'multiple_choice', 500.00, 'Exploration & Planning', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'Closure plan document, financial surety records', 'No closure plan or financial assurance.', 'A draft closure plan exists, but funding is not secured.', 'Approved closure plan in place with partial financial assurance.', 'Comprehensive closure plan with full financial assurance; reviewed periodically.', 'Fully funded closure and reclamation plan meeting all requirements.'),
(99, 1, 'Are local communities involved in planning for mine closure and reclamation (e.g., deciding post-mining land use)?', 'multiple_choice', 300.00, 'Exploration & Planning', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'Community consultation records, agreements on closure', 'No community consultation on closure plans.', 'Community consultation on closure is planned but not done yet.', 'Some community input on closure obtained informally.', 'Communities consulted on closure plans; feedback being incorporated.', 'Communities actively co-plan closure and agree on post-mining land use.'),
(100, 1, 'Does the company annually report its economic contributions (e.g., taxes, royalties and other payments to governments)?', 'multiple_choice', 250.00, 'Economic Development', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'Annual financial/sustainability reports, EITI disclosures', 'No annual reporting of economic contributions.', 'Economic contributions tracked internally, but no public annual report.', 'Some information on contributions published irregularly or incompletely.', 'Annual reports on economic contributions published; improving detail/availability.', 'Full annual reports of all payments are published and easily accessible.'),
(101, 1, 'Does the company publicly disclose its payments to governments and ensure these reports are accessible to local communities?', 'multiple_choice', 250.00, 'Economic Development', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'Public payment reports, EITI reports, audit statements', 'No public disclosure of payments to governments.', 'Plans to disclose payment data, but not yet implemented.', 'Basic payment data disclosed to authorities or EITI, limited public access.', 'Detailed payment reports published regularly; enhancing accessibility for communities.', 'All payments to governments are transparently disclosed and readily accessible to the public.'),
(102, 1, 'Is there a strategy to increase local employment and procurement (local content)?', 'multiple_choice', 250.00, 'Economic Development', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'Procurement reports, labor statistics', 'No local employment or procurement strategy.', 'Strategy drafted but not yet implemented.', 'Strategy implemented with some local hiring and purchasing.', 'Effective local content strategy with increasing local participation.', 'Strategy fully achieved with high local employment and supply chain integration.'),
(103, 1, 'Does the company have programs for community development on economic diversification?', 'multiple_choice', 250.00, 'Economic Development', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'CSR reports, sustainability report', 'No programs for economic diversification.', 'Programs planned but not yet started.', 'Some programs implemented with limited reach.', 'Active programs supporting various local economic activities.', 'Comprehensive programs successfully creating independent local economies.'),
(104, 1, 'Does the company have anti-corruption and anti-bribery policies implemented across all operations?', 'multiple_choice', 400.00, 'Business Conduct', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'Code of ethics, anti-bribery policy', 'No anti-corruption or anti-bribery policies.', 'Policies exist but are not communicated or enforced.', 'Policies communicated to employees; some enforcement mechanisms in place.', 'Strict enforcement of policies with regular audits and training.', 'Zero-tolerance culture with comprehensive compliance and independent verification.'),
(105, 1, 'How does the company conduct ethics and compliance training for employees and business partners/stakeholders?', 'multiple_choice', 250.00, 'Business Conduct', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'Training schedule, training materials', 'No training provided on ethics or compliance.', 'Training provided only to senior management or irregularly.', 'Regular training for employees; limited training for partners.', 'Comprehensive training for all employees and key partners.', 'Continuous training and certification for all employees and supply chain partners.'),
(106, 1, 'Does the company have a safe and published report on whistleblowing mechanism for reporting violations?', 'multiple_choice', 300.00, 'Business Conduct', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'Whistleblowing report system, case reports', 'No whistleblowing mechanism exists.', 'Mechanism exists but is not anonymous or widely known.', 'Anonymous mechanism available and communicated to employees.', 'Mechanism fully operational, accessible to external stakeholders, and trusted.', 'Independent third-party mechanism with guaranteed protection and transparent reporting.'),
(107, 1, 'Are contractors and suppliers required to comply with the company''s code of ethics and ESG policies?', 'multiple_choice', 250.00, 'Business Conduct', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'Contract agreements, vendor audits, vendor socialisation', 'No requirements for contractors/suppliers.', 'Requirements included in contracts but not monitored.', 'Compliance monitored through self-assessments or occasional checks.', 'Regular audits of contractors/suppliers for compliance.', 'Strict compliance required as a condition of contract, with corrective actions enforced.'),
(108, 1, 'How does the company ensure Free, Prior, and Informed Consent (FPIC) from the community before operation activities begin?', 'multiple_choice', 500.00, 'Community Wellbeing', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'Agreement documents, public consultation minutes', 'No FPIC sought.', 'FPIC process started but incomplete.', 'FPIC obtained for major activities only.', 'FPIC obtained for all activities with ongoing consultation.', 'Continuous FPIC process fully integrated into all operational phases.'),
(109, 1, 'Is there a transparent and publicly accessible community complaint mechanism?', 'multiple_choice', 300.00, 'Community Wellbeing', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'Grievance log reports, follow-up actions', 'No complaint mechanism.', 'Mechanism exists but is difficult to access or opaque.', 'Mechanism accessible with some record keeping.', 'Transparent mechanism with regular feedback and resolution tracking.', 'Fully accessible, independent mechanism with public reporting of resolutions.'),
(110, 1, 'Does the company invest in public services/CSR (education, health, clean water) for surrounding communities?', 'multiple_choice', 250.00, 'Community Wellbeing', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'CSR reports, MoU with local government', 'No investment in public services or CSR.', 'Ad-hoc donations with no strategic plan.', 'Planned CSR investments in key areas (education, health).', 'Strategic long-term investments aligned with community needs.', 'Transformative investments with measurable long-term positive impacts.'),
(111, 1, 'Does the company identify and mitigate the social impacts of operations?', 'multiple_choice', 300.00, 'Community Wellbeing', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'Social AMDAL, social impact reports', 'No social impact identification.', 'Social impacts identified but not mitigated.', 'Mitigation plans in place for major impacts.', 'Comprehensive management of all social impacts with community input.', 'Proactive social impact management enhancing community well-being.'),
(112, 1, 'Does the company implement an OHS Management System (e.g., ISO 45001) across all operations?', 'multiple_choice', 500.00, 'Working Conditions', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'OHS certificate, audit reports', 'No OHS management system.', 'Basic safety rules in place but no formal system.', 'OHS system implemented but not certified.', 'Certified OHS system (e.g., ISO 45001) in place.', 'World-class safety culture with leading indicators and continuous improvement.'),
(113, 1, 'How does the company ensure fair wages and working conditions for all workers, including related contractors?', 'multiple_choice', 300.00, 'Working Conditions', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'HR policies, employment contracts', 'No policy on fair wages or working conditions.', 'Compliance with minimum wage only.', 'Fair wages and conditions for permanent staff; contractors vary.', 'Fair wages and conditions enforced for all workers including contractors.', 'Exceeds living wage standards with excellent conditions for entire workforce.'),
(114, 1, 'Is there any regular safety training and reporting of work accident?', 'multiple_choice', 300.00, 'Working Conditions', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'Training records, LTIFR/TRIFR data', 'No safety training or accident reporting.', 'Irregular training and limited reporting.', 'Regular training and mandatory accident reporting.', 'Comprehensive training matrix and detailed accident analysis.', 'Safety embedded in culture; near-miss reporting and proactive prevention.'),
(115, 1, 'Does the company have a diversity and inclusion (gender equality) policy in the workplace?', 'multiple_choice', 150.00, 'Working Conditions', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'Diversity report, gender workforce data', 'No diversity or inclusion policy.', 'Policy exists but not actively implemented.', 'Active programs to promote diversity and inclusion.', 'Measurable targets for diversity and inclusion achieved.', 'Inclusive culture recognized as a benchmark in the industry.'),
(116, 1, 'Does the company have an Environmental Management System (ISO 14001) and carbon emission reduction targets?', 'multiple_choice', 300.00, 'Environmental Responsibility', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'ISO certificate, emission reports', 'No environmental management system or targets.', 'Basic environmental controls; no formal system.', 'ISO 14001 implemented; targets being developed.', 'ISO 14001 certified; emission reduction targets set.', 'Certified system with ambitious science-based targets achieved.'),
(117, 1, 'How does the company manage hazardous waste and tailings to prevent environmental pollution?', 'multiple_choice', 500.00, 'Environmental Responsibility', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'Waste management, monitoring results', 'No specific management of hazardous waste/tailings.', 'Basic containment but high risk of pollution.', 'Managed according to regulations; some risks remain.', 'Best practice management with strict monitoring.', 'State-of-the-art management with zero discharge/pollution track record.'),
(118, 1, 'Does air, water, and soil quality be monitored periodically in the operational area?', 'multiple_choice', 300.00, 'Environmental Responsibility', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'Monitoring reports, laboratory results', 'No environmental monitoring.', 'Ad-hoc monitoring when complaints arise.', 'Regular monitoring for compliance purposes.', 'Comprehensive monitoring program with public data access.', 'Real-time monitoring and transparent reporting exceeding regulations.'),
(119, 1, 'Does the company have a biodiversity conservation program around the operation area?', 'multiple_choice', 300.00, 'Environmental Responsibility', false, NULL, '2025-12-08 10:47:50.362266+00', '2025-12-08 10:47:50.362266+00', 'Conservation reports, sustainability report', 'No biodiversity conservation program.', 'Basic rehabilitation of mined areas only.', 'Conservation plan exists for specific species/areas.', 'Comprehensive biodiversity management plan implemented.', 'Net positive impact on biodiversity demonstrated and verified.');